### ISSUE TITLE
Changement de binôme et date limite

### ISSUE THREAD

**Issue by ValentinPrive** [bflorat/tp-miage-2024#2]
Bonjour,

Lors du TP mardi dernier (27 février), Alex et moi n'avons pas réussi à travailler sur nos PCs, par manque de puissance de ceux-ci.
Vous nous avez alors permis de nous joindre à d'autres binômes.
Nous avons bien avancé dans ces nouveaux groupes de 3 et voudrions savoir si nous pouvons garder ces groupes de 3 pour le rendu final du TP, ou si nous devons recommencer le TP de notre côté, Alex et moi. Cela nous prendrait plus de temps car nous devrions reprendre de zéro, et de mon côté je n'ai pas de PC suffisamment puissant pour travailler sur ce TP.

De plus, nous souhaiterions savoir quelle est la date limite pour rendre ce TP.

Merci par avance pour votre réponse.
Cordialement.

Valentin PRIVÉ
M1 MIAGE Classique

**Comment by bflorat** [comment]
Bonjour, à titre exceptionnel, vous pouvez rester sur les deux trinômes.

J'enverai des précisions sous peu.

Bien à vous
